//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP_Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Course = new HashSet<Course>();
            this.Result = new HashSet<Result>();
        }
    
        public int Id { get; set; }
        [DisplayName("FirstName")]
        [Required(ErrorMessage = "This Field is Required")]
        public string FisrtName { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string LastName { get; set; }
        public string Email { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Password { get; set; }
        public short AccountType { get; set; }
        public Nullable<int> CohortId { get; set; }
    
        public virtual Cohort Cohort { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
