

//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OOP_Final_Project.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DBModels : DbContext
{
    public DBModels()
        : base("name=DBModels")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Account> Account { get; set; }

    public virtual DbSet<Cohort> Cohort { get; set; }

    public virtual DbSet<Course> Course { get; set; }

    public virtual DbSet<Exam> Exam { get; set; }

    public virtual DbSet<Result> Result { get; set; }

}

}

